name: Unit Tests
env:
  DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
  SUPERGOOD_CLIENT_ID: ${{ secrets.STAGING_SUPERGOOD_CLIENT_ID }}
  SUPERGOOD_CLIENT_SECRET: ${{ secrets.STAGING_SUPERGOOD_CLIENT_SECRET }}
  SUPERGOOD_BASE_URL: ${{ vars.SUPERGOOD_BASE_URL }}
  SUPERGOOD_ORGANIZATION_ID: ${{ vars.SUPERGOOD_ORGANIZATION_ID }}
on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 18]
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Run Tests
        run: |
          yarn install
          yarn clean
          yarn build
          yarn test
